#1 Modify chips sold histogram to reflect percentages instead of counts
linxicindyzeng/template_archive pull request #2
Opened 2024-08-30 04:24 UTC by linxicindyzeng

Changes made:

- In [clean_data.py](https://github.com/linxicindyzeng/template_archive/blob/master/data/code/clean_data.py), modify the code for chips_sold.pdf to reflect percentages instead of counts
- Run [data/make.py](https://github.com/linxicindyzeng/template_archive/blob/master/data/make.py) to update the data folder with the new histogram 
- Run [paper_slides/make.py](https://github.com/linxicindyzeng/template_archive/blob/master/paper_slides/make.py) to reflect the change in the paper

Deliverables:
- [New histogram for chips sold](data/output/chips_sold.pdf)
- [Paper updated with new histogram for chips sold](paper_slides/output/paper.pdf)

@ShiqiYang2022 Hi Shiqi, please let me know if anything needs to be modified. Thanks for reviewing!

2024-08-30 15:49 UTC, ShiqiYang2022 requested changes
@linxicindyzeng Thanks for all of the work here! 

I have several comments, some of them might not be documented in the RA manual, but they are our lab's routines in doing a pull request.

1. Please rename your Pull request to "Pull request for #1: Modify chips sold histogram to reflect percentages instead of counts" or "PR for #1: ...". Every PR's title should have such format.
2. Every PR should begin with "Closes #IssueNumber." so that it will links to the related issue. See [here](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue). Please revise your https://github.com/linxicindyzeng/template_archive/pull/2#issue-2496200276 accordingly.
3. Please revise your https://github.com/linxicindyzeng/template_archive/pull/2#issue-2496200276 to display files' permanent links (ref [here](https://docs.github.com/en/repositories/working-with-files/using-files/getting-permanent-links-to-files)) on the branch (instead of `master`).
4. The link for the histogram and the paper is expired in https://github.com/linxicindyzeng/template_archive/pull/2#issue-2496200276, please double check.
5. When the issue request changes in the input of the paper, it would be great to deliver a [draftable difference](https://www.draftable.com/compare). Could you please revise your https://github.com/linxicindyzeng/template_archive/pull/2#issue-2496200276 accordingly to include a draftable difference link?
6. I left some other comments about the files that should not be committed in the thread.

After you've addressed those issues, please tag me again and I'll have a final review. Thanks!

2024-08-30 15:49 UTC, ShiqiYang2022 commented on paper_slides/code/slides.fdb_latexmk
@linxicindyzeng Why this file should be committed? I think this might be a commit by mistake.

2024-08-30 15:49 UTC, ShiqiYang2022 commented on paper_slides/code/slides.pdf
@linxicindyzeng Why this file should be committed? I think this might be a commit by mistake.

2024-08-30 15:49 UTC, ShiqiYang2022 commented on paper_slides/code/slides.synctex.gz
@linxicindyzeng Why this file should be committed? I think this might be a commit by mistake.

2024-08-30 15:49 UTC, ShiqiYang2022 commented on paper_slides/code/slides.log
@linxicindyzeng Why this file should be committed? I think this might be a commit by mistake.

2024-08-30 15:49 UTC, ShiqiYang2022 commented on setup/download_stata_ado.do
@linxicindyzeng Why this file should be committed? I think this might be a commit by mistake.

2024-08-30 15:49 UTC, ShiqiYang2022 commented on texput.log
@linxicindyzeng Why this file should be committed? I think this might be a commit by mistake.

2024-08-30 23:42 UTC, linxicindyzeng commented
@ShiqiYang2022  Hi Shiqi, thank you so much for the careful review and comments! I've made modifications as suggested. Please let me know if more changes are needed.

2024-08-30 23:55 UTC, ShiqiYang2022 commented on paper_slides/code/slides.fdb_latexmk
@linxicindyzeng  Usually, the conversation thread should be resolved by the reviewer. What we do is,

If the assignee accept the review, he addressed in a commit and tag the reviewer with providing the exact commit hash number. For example, see [here](https://github.com/gslab-econ/newsworthy/pull/249#discussion_r1708139432).

If the assignee disagree with the review, he replies the reviewer with the specific reason. For example, see [here](https://github.com/gentzkow/GentzkowLabTemplate/pull/14#discussion_r1705560509).

The reviewer then decides whether the conversation is good to go or not. We don't recommend the assignee to resolve the conversation himself.

2024-08-30 23:56 UTC, ShiqiYang2022 approved these changes
Thanks @linxicindyzeng! The changes all looks good from my side hence I'm approving.

I have one comment in a re-opened thread, it's also about our work routine in a PR.

2024-08-30 23:59 UTC, linxicindyzeng commented on paper_slides/code/slides.fdb_latexmk
@ShiqiYang2022 Sorry! You're right, that makes much more sense. Thank you for explaining it in detail.

2024-08-31 00:00 UTC, ShiqiYang2022 commented
I think now you can feel free to "squash and merge" this branch back to `master`. After we merged back to `master`, please post a summary comment in #1 to summarize what you've done in the issue and its associated PR.

2024-08-31 00:02 UTC, ShiqiYang2022 commented on paper_slides/code/slides.fdb_latexmk
@linxicindyzeng No worries, that's exactly what a practice task meant for! I am now resolving the thread.

2024-09-03 18:21 UTC, merged